USE SISTEMA_CONTROLE
GO

CREATE TABLE CIDADES(
	ID_CIDADE INT IDENTITY(1,1) NOT NULL,
	NOME_CIDADE VARCHAR(30) NOT NULL,
	DDD TINYINT NULL,
	ESTADO VARCHAR(20) NOT NULL

	CONSTRAINT PK_ID_CIDADE PRIMARY KEY (ID_CIDADE)
)
GO

CREATE TABLE COMERCIOS( ----------------------------------------------------------------------
	ID_COMERCIO INT IDENTITY(1,1) NOT NULL,
	NOME_COMERCIO VARCHAR(30) NOT NULL,
	TELEFONE1 VARCHAR(11) NOT NULL,
	TELEFONE2 VARCHAR(11) NULL,
	EMAIL VARCHAR(30) NULL,
	DT_CADASTRO DATETIME NOT NULL,
	ID_CIDADE INT NOT NULL,
	COMERCIO_ATIVO BIT NOT NULL

	CONSTRAINT PK_ID_COMERCIO PRIMARY KEY (ID_COMERCIO),

	CONSTRAINT FK_ID_CIDADE__COMERCIOS FOREIGN KEY (ID_CIDADE)
	REFERENCES CIDADES (ID_CIDADE)
)
GO

CREATE TABLE GASTOS_MENSAIS(
	ID_GASTO INT IDENTITY(1,1) NOT NULL,
	DESC_GASTO VARCHAR(500) NULL,
	VALOR_GASTO NUMERIC(7,2) NOT NULL,
	DT_GASTO DATETIME NOT NULL,
	ID_COMERCIO INT NOT NULL,
	MES_REFERENCIA TINYINT NULL,
	FIXO BIT NOT NULL,
	GASTO_ATIVO BIT NOT NULL

	CONSTRAINT PK_ID_GASTO PRIMARY KEY (ID_GASTO),

	CONSTRAINT FK_ID_COMERCIO__GASTOS_MENSAIS FOREIGN KEY (ID_COMERCIO)
	REFERENCES COMERCIOS (ID_COMERCIO)
)
GO

CREATE TABLE PRODUTOS(
	ID_PRODUTO INT IDENTITY(1,1) NOT NULL,
	NOME_PRODUTO VARCHAR(50) NOT NULL,
	DESC_PRODUTO VARCHAR(255) NULL,
	MARCA VARCHAR(15) NULL,
	PRODUTO_ATIVO BIT NOT NULL

	CONSTRAINT PK_ID_PRODUTO PRIMARY KEY (ID_PRODUTO)
)
GO

CREATE TABLE COMPRAS( 
	ID_COMPRA INT IDENTITY(1,1) NOT NULL,
	ID_COMERCIO INT NOT NULL,
	DT_COMPRA DATETIME NOT NULL,
	VALOR_TOTAL_COMPRA NUMERIC(7,2) NOT NULL


	CONSTRAINT PK_ID_COMPRA PRIMARY KEY (ID_COMPRA),

	CONSTRAINT FK_ID_COMERCIO__COMPRAS FOREIGN KEY (ID_COMERCIO)
	REFERENCES COMERCIOS (ID_COMERCIO)
)
GO

CREATE TABLE COMPRAS_PRODUTOS(
	ID_COMPRA INT NOT NULL,
	ID_PRODUTO INT NOT NULL,
	QTD_PRODUTO INT NOT NULL,
	PRECO_UN NUMERIC(7,2) NOT NULL

	CONSTRAINT FK_ID_COMPRA__COMPRAS_PRODUTOS FOREIGN KEY (ID_COMPRA)
	REFERENCES COMPRAS (ID_COMPRA),

	CONSTRAINT FK_ID_PRODUTO__COMPRAS_PRODUTOS FOREIGN KEY (ID_PRODUTO)
	REFERENCES PRODUTOS (ID_PRODUTO)
)
GO

CREATE TABLE ENTRADAS_ESTOQUE(
	ID_ENTRADA INT IDENTITY(1,1) NOT NULL,
	ID_PRODUTO INT NOT NULL,
	QTD_ENTRADA SMALLINT NOT NULL,
	QTD_ATUAL SMALLINT NOT NULL,
	DT_ENTRADA DATETIME NOT NULL,
	VALOR_UN NUMERIC(7,2) NULL,
	VALOR_TOTAL NUMERIC (7,2) NULL,
	ENTRADA_ATIVA BIT NOT NULL

	CONSTRAINT PK_ID_ENTRADA PRIMARY KEY (ID_ENTRADA),

	CONSTRAINT FK_ID_PRODUTO__ENTRADAS_ESTOQUE FOREIGN KEY (ID_PRODUTO)
	REFERENCES PRODUTOS (ID_PRODUTO)
)
GO

CREATE TABLE SAIDAS_ESTOQUE(
	ID_SAIDA INT IDENTITY(1,1) NOT NULL,
	ID_PRODUTO INT NOT NULL,
	QTD_SAIDA SMALLINT NOT NULL,
	VALOR_TOTAL NUMERIC (7,2) NULL,
	DT_SAIDA DATETIME NOT NULL

	CONSTRAINT PK_ID_SAIDA PRIMARY KEY (ID_SAIDA),

	CONSTRAINT FK_ID_PRODUTO__SAIDAS_ESTOQUE FOREIGN KEY (ID_PRODUTO)
	REFERENCES PRODUTOS (ID_PRODUTO)
)
GO